version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    exclude-paths:
      - "tests/sample-files/*"
      - "tests/sample-files/**/*"
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
    exclude-paths:
      - "tests/sample-files/*"
      - "tests/sample-files/**/*"
